### ISSUE TITLE
onTimeout behaviour confusing after 0.8.4

### ISSUE THREAD

**Issue by rdghickman** [vsilaev/tascalate-concurrent#26]
Hi, I've been using this library for a while and recently dug out some project from over a year ago and upgraded from 0.8.4 to 0.9.6. The behaviour for `onTimeout` is no longer doing what it used to and I'm confused if I'm doing it wrong. The simplest test case I can see is this:

```java
    @Test
    public void test()
    throws ExecutionException, InterruptedException
    {
        String message = "test";
        CompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {
            try {
                Thread.sleep(500);
            } catch (Exception e) {
                e.printStackTrace();
            }
            return message;
        });

        Promise<String> promise1 = Promises.from(future).orTimeout(Duration.ofSeconds(1));

        assertEquals(message, promise1.get());
    }
```

The `promise1.get()` reports a failure due to a `CancellationException` immediately. The code works and succeeds in 0.8.4. Any suggestions?

**Comment by vsilaev** [comment]
It's related to the uniform handling of the promises returned from operations (like thenApply / thenRun and orTimeout / onTimeout); now every operation yields a new independent promise (unless explicitly specified otherwise via `dependent()` and corresponding overloaded method). Try this:
```java
        ...      
        Promise<String> promise1 = Promises.from(future);
        Promise<String> promise2 = promise1.orTimeout(Duration.ofSeconds(1));
        assertEquals(message, promise1.get());
```

Or better yet for your use-case:
```java
        ...      
        Promise<String> promise1 = 
        Promises
        .from(future)
        .dependent()
        .orTimeout(Duration.ofSeconds(1), true /*CANCEL ON TIMEOUT*/, true /* ENLIST ORIGINAL PROMISE*/)
        assertEquals(message, promise1.get());
```

This behavior is intended and documented - please find lines "It's important to mention the crucial difference between Promise.orTimeot / onTimeout and CompletableFuture.orTimeout / completeOnTimeout in Java 9+." in README of the library.
It was buggy in 0.8.4, so in in your use case it was "accidentally correct" previously.

**Comment by vsilaev** [comment]
My apologizes for the late response - for some reason GitHub stopped notifying me about new issues via email.
