### ISSUE TITLE
Promises.all - List type argument

### ISSUE THREAD

**Issue by ajurcik** [vsilaev/tascalate-concurrent#7]
Hi Valery,

I hope you are doing well.
I just tried to create an all promise from a list of promises. See the follwing code:
```
List<Promise<T>> promises = new ArrayList<>();
Promise<?> all = Promises.all(promises);
```
And this does not compile since the generic type of the `promises` argument is too narrow. Specifically, we would need it to be `Promise<T> all(List<? extends CompletionStage<? extends T>> promises)`. Maybe `Promise<T> all(Collection<? extends CompletionStage<? extends T>> promises)` could also work.

Best, Adam

**Comment by vsilaev** [comment]
Hello,

Reviewing, will provide an update shortly...

**Comment by vsilaev** [comment]
Adam,

I've just committed a fix: 
`List<CompletionStage<? extends T>> promises`
...argument type is widening as
`List<? extends CompletionStage<? extends T>> promises`

Please verify. Note, that List -> Collection widening is not possible, because we must ensure positional (index-based) access in return value.

Waiting for your confirmation -- will release a minor build afterwards while this change is fully backward-compatible.

Regards,
Valery

**Comment by ajurcik** [comment]
Hi Valery, verified, works for me. Thank You.
